import subprocess

import requests

from agent.analysis.patch_validator import EXCLUDE_REPRO


def _git(repo_path, token: str, *args: str) -> str:
    proc = subprocess.run(["git", "-C", str(repo_path), *args], capture_output=True, text=True)
    if proc.returncode != 0:
        raise RuntimeError(f"git {args[0]} failed: {proc.stderr.replace(token, '***')[-800:]}")
    return proc.stdout


def create_pr(issue, repo_path, summary: str, token: str, base_branch: str | None = None) -> str:
    """Commit the working-tree changes to a new branch, push, and open a PR.
    Requires push access to the repo (use a fork + adjust `head` otherwise)."""
    if not token:
        raise ValueError("GITHUB_TOKEN is required to open a PR")

    api = f"https://api.github.com/repos/{issue.owner}/{issue.repo}"
    headers = {"Accept": "application/vnd.github+json", "Authorization": f"Bearer {token}"}

    if not base_branch:
        r = requests.get(api, headers=headers, timeout=30)
        r.raise_for_status()
        base_branch = r.json()["default_branch"]

    branch = f"agent/fix-issue-{issue.number}"
    _git(repo_path, token, "checkout", "-b", branch)
    _git(repo_path, token, "add", "-A", "--", ".", EXCLUDE_REPRO)
    _git(repo_path, token, "commit", "-m", f"Fix #{issue.number}: {issue.title}")

    push_url = f"https://x-access-token:{token}@github.com/{issue.owner}/{issue.repo}.git"
    _git(repo_path, token, "push", push_url, f"{branch}:{branch}")

    body = f"{summary}\n\nCloses #{issue.number}\n\n_Generated by an autonomous agent. Please review carefully._"
    resp = requests.post(f"{api}/pulls", headers=headers, timeout=30, json={
        "title": f"Fix #{issue.number}: {issue.title}",
        "head": branch, "base": base_branch, "body": body,
    })
    resp.raise_for_status()
    return resp.json()["html_url"]